apiVersion: apps/v1
kind: Deployment
metadata:
  name: portifolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portifolio
  template:
    metadata:
      labels:
        app: portifolio
    spec:
      imagePullSecrets:
        - name: ecr-portifolio
      containers:
        - name: portifolio
          image: 891377156618.dkr.ecr.us-east-1.amazonaws.com/portifolio:{{tag}}
          resources:
            requests:
              cpu: "30m"
              memory: "300Mi"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 120 